language ja_JP.utf-8
set background=light
colorscheme iceberg
" MacVim workaround to fix menu language
source $VIMRUNTIME/delmenu.vim
set langmenu=ja_JP.utf-8
source $VIMRUNTIME/menu.vim
set guifont=UDEVGothic35LG-Regular:h14
set linespace=5
