language ja_JP.utf-8
if has('macunix')
	" MacVim workaround to fix menu language
	source $VIMRUNTIME/delmenu.vim
	set langmenu=ja_JP.utf-8
	source $VIMRUNTIME/menu.vim
endif
set guifont=UDEVGothic35LG-Regular:h14
set linespace=5
