if filereadable(expand('$VIMRUNTIME/defaults.vim'))
  source $VIMRUNTIME/defaults.vim
endif

syntax on
set number

" Visualize whitespaces
" \u21e5\u00a0\u00a0 (nbsp)
set listchars=tab:⇥  ,trail:•,
highlight SpecialKey ctermfg=gray
highlight NonText ctermfg=gray
set list
