set number
" don't use octal
set nrformats=

" Visualize whitespaces
" recent version supports 3 chars for tab.
set listchars=tab:⇥ ,trail:•,
highlight SpecialKey ctermfg=gray
highlight NonText ctermfg=gray
set list

nnoremap ; :
nnoremap : ;
vnoremap ; :
vnoremap : ;

" tclip
command! -range=% Tclip <line1>,<line2>write !tclip
