on: [push]

env:
  DOT_DATA_DIR: .local/share/dotfiles

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - run: sudo apt install -y shellcheck shfmt
      - uses: actions/checkout@v4
      - run: shellcheck $DOT_DATA_DIR/dot
      - run: shfmt -d $DOT_DATA_DIR/dot

  test:
    needs: lint
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: /home/runner
    steps:
      - uses: actions/checkout@v4

      - name: test clone default
        run: DEBUG=1 BRANCH='${{ github.ref_name }}' "${{ github.workspace }}/$DOT_DATA_DIR/dot" clone https://github.com/honai/dotfiles.git

      - name: test `dot status`
        run: $HOME/$DOT_DATA_DIR/dot status

      - name: test `dot init sub`
        run: $HOME/$DOT_DATA_DIR/dot init sub
